//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PITPM4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TRPOEntities : DbContext
    {
       
            public DbSet<Clothing> Clothings { get; set; }

            // Другие DbSets и методы контекста
        

        public TRPOEntities() : base("name=TRPOEntities")
        {

        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Администратор> Администратор { get; set; }
        public virtual DbSet<Администратор_Одежда_Покупатель> Администратор_Одежда_Покупатель { get; set; }
        public virtual DbSet<Возврат> Возврат { get; set; }
        public virtual DbSet<Закупка> Закупка { get; set; }
        public virtual DbSet<Инвентаризация> Инвентаризация { get; set; }
        public virtual DbSet<Классификация> Классификация { get; set; }
        public virtual DbSet<Менеджер> Менеджер { get; set; }
        public virtual DbSet<Одежда> Одежда { get; set; }
        public virtual DbSet<Оформление_товара> Оформление_товара { get; set; }
        public virtual DbSet<Покупатель> Покупатель { get; set; }
        public virtual DbSet<Продавец_Консультант> Продавец_Консультант { get; set; }
        public virtual DbSet<Склад> Склад { get; set; }
    }
}
