//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PITPM4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Администратор
    {
        public int ID { get; set; }
        public string Имя { get; set; }
        public string Фамилия { get; set; }
        public string Почта { get; set; }
        public string Телефон { get; set; }
        public string Роль { get; set; }
    }
}
