//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PITPM4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Возврат
    {
        public int ID { get; set; }
        public string Дата { get; set; }
        public string Сумма { get; set; }
        public string Причина { get; set; }
        public string Статус { get; set; }
        public Nullable<int> Менеджер_ID { get; set; }
        public Nullable<int> Закупка_ID { get; set; }
    }
}
