//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PITPM4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Инвентаризация
    {
        public int ID { get; set; }
        public string Дата { get; set; }
        public string Примечания { get; set; }
        public Nullable<int> Продавец_консультант_ID { get; set; }
        public Nullable<int> Склад_ID { get; set; }
    }
}
