//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PITPM4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Одежда
    {
        public int ID { get; set; }
        public string Название { get; set; }
        public string Описание { get; set; }
        public string Цена { get; set; }
        public string Размер { get; set; }
        public Nullable<int> Закупка_ID { get; set; }
        public Nullable<int> Классификация_ID { get; set; }
        public Nullable<int> Администратор_ID { get; set; }
    }
}
