//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PITPM4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Оформление_товара
    {
        public int ID { get; set; }
        public string Статус { get; set; }
        public string Фамилия { get; set; }
        public Nullable<int> Одежда_ID { get; set; }
        public Nullable<int> Покупатель_ID { get; set; }
        public Nullable<int> Продавец_Консультант_ID { get; set; }
    }
}
