//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PITPM4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Склад
    {
        public int ID { get; set; }
        public string Наименование { get; set; }
        public string Емкость { get; set; }
        public string Количество_одежды { get; set; }
        public Nullable<int> Менеджер_ID { get; set; }
    }
}
